-- Run this once in your Supabase project's SQL Editor.

create table if not exists contacts (
  id bigint generated by default as identity primary key,
  number integer not null,
  business text not null,
  address text,
  phone text not null unique,
  created timestamptz default now(),
  called boolean default false,
  "lastCalled" timestamptz,
  notes text default '',
  recall boolean default false,
  lead boolean default false
);

-- Row Level Security: required by Supabase before the anon (public) key
-- can read/write. This policy allows full access to anyone with your
-- anon key, which matches the app's current no-login design.
alter table contacts enable row level security;

create policy "Allow all access"
on contacts
for all
using (true)
with check (true);
